# Generated by Django 3.2.10 on 2021-12-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0002_image'),
    ]
    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
