# Generated by Django 3.2.10 on 2021-12-28 11:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0006_alter_image_position'),
    ]
    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(),
        ),
    ]
