# Generated by Django 3.2.10 on 2022-04-16 15:31

from django.db import migrations


def copy_to_place_id(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        place.place_id = place.placeId
        place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20220416_2016'),
    ]

    operations = [
        migrations.RunPython(copy_to_place_id),
    ]
