# Generated by Django 3.2.10 on 2022-04-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_remove_place_placeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
