# Generated by Django 3.2.10 on 2022-04-16 16:08

from django.db import migrations


def copy_to_slug(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        place.slug = place.place_id
        place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_place_slug'),
    ]

    operations = [
        migrations.RunPython(copy_to_slug),
    ]
